services:
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://backend:5000
    ports:
      - "3001:5173"
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - "5002:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
